import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import Settings from "./components/Settings";
import { DarkModeProvider } from "./components/DarkModeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DarkModeProvider>
      <html lang="en" className="scroll-smooth">
        <body className={`${inter.className} flex relative`}>
          <div className={` h-full overflow-visible z-50 absolute sm:relative`}>
            <Sidebar />
          </div>
          <div className={`h-screen overflow-y-scroll`}>{children}</div>
          <Header />
          <Settings />
        </body>
      </html>
    </DarkModeProvider>
  );
}
